## Библиотека numpy. Вычислительные задачи- предлекционный материал

## Задание 1
### "Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))"

In [3]:
import numpy as np
n = int(input("Введи число ")) # Принимает на вход чилсо с которого начнётся Функция (arange)
a = np.arange(n-1,-1,-1)
print (a)

Введи число 10
[9 8 7 6 5 4 3 2 1 0]


## Задание 2

### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
n=int(input())
matrix=np.diag(np.arange(n,0,-1))
print(matrix)
print (sum(matrix))
print (format(sum(sum(matrix))))

11
[[11  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  1]]
[11 10  9  8  7  6  5  4  3  2  1]
66


## Задание 3
### Решите систему уравнений:

In [26]:
from numpy import linalg
a=np.array([[4,2,1],[1,3,0],[0,5,4]])
b=np.array([4,12,-3])
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4
### В материалах занятия раздел “Задача 4 домашнего задания”

In [2]:
import numpy as np

def cosine( users_stats, next_user_stats ):
    # длины векторов
    users_stats_Length = np.linalg.norm( users_stats )
    next_user_stats_Length = np.linalg.norm( next_user_stats )
    return np.dot( users_stats, next_user_stats ) / ( users_stats_Length * next_user_stats_Length )

users = np.array([
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ])
new_user = np.array ([0, 1, 2, 0, 0, 0])

cosines = []

for user in users:
    cosines.append(cosine(new_user, user))

maxValue = np.amax(cosines)
    
for i in range(len(cosines)):
    if (cosines[i] == maxValue):
        print(i)

7
